import type { Metadata } from "next";
import "../globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <div className="overflow-hidden rounded-[0.5rem] border bg-background shadow">
          {children}
        </div>
  );
}
